{"name": "test_verify_error_message_with_invalid_credentials", "status": "failed", "statusDetails": {"message": "AssertionError: The error message for invalid credentials is incorrect.\nassert 'Incorrect email or password.' == 'Incorrect'\n  \n  - Incorrect\n  + Incorrect email or password.", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"871c0640ee83b31b5e13d362a68121af\")>\n\n    def test_verify_error_message_with_invalid_credentials(driver):\n        # Verify error message when login attempt with invalid credentials\n        login_page = LoginPage(driver)\n        # Attempt to login with invalid email and password\n        login_page.login(TestData.WRONG_EMAIL, TestData.WRONG_PASSWORD)\n        # Assert the error message is displayed\n>       assert login_page.get_text(LoginPageLocators.LOGIN_ERROR_MSG) == \"Incorrect\", \"The error message for invalid credentials is incorrect.\"\nE       AssertionError: The error message for invalid credentials is incorrect.\nE       assert 'Incorrect email or password.' == 'Incorrect'\nE         \nE         - Incorrect\nE         + Incorrect email or password.\n\ntests\\test_login.py:33: AssertionError"}, "start": 1726248666833, "stop": 1726248671392, "uuid": "d419b162-3550-4f0b-aff6-d98bff327027", "historyId": "02d1f4d059022f8176ed810b654a99f3", "testCaseId": "02d1f4d059022f8176ed810b654a99f3", "fullName": "tests.test_login#test_verify_error_message_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Laptop-Diego"}, {"name": "thread", "value": "25920-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}